name: Build and publish Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Allow writing to GitHub Packages (GHCR)
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch support, safe)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository | lower }}:latest,ghcr.io/${{ github.repository_owner }}/${{ github.repository | lower }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
